baseURL = 'http://example.org/'
languageCode = 'zh'
title = '我的HUGO'
theme = 'anatole'
enableRobotsTXT = true
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  profilePicture='images/profile.jpg'

[languages]   
  [languages.zh]     
    disabled = false
    languageCode = 'zh-TW'     
    languageDirection = 'ltr'     
    languageName = '繁體中文'     
    weight = 1    
    [languages.zh.params]
      Title='蔡仔為 Victor'
      description='一位 Java工程師'
  [languages.en]     
    disabled = false     
    languageCode = 'en-US'     
    languageDirection = 'ltr'     
    languageName = 'English'     
    weight = 2     
    [languages.en.params]       
      Title = 'Victor Tsai'
      description = 'testing description'