baseURL = 'https://victorDeveloper0821.github.io/'
## 網站的 title 
title = '工程獅日常 - Victor 的技術天地'
author='Victor Tsai'
enableEmoji=true
isMultiLingual=true
isTranslated=true
googleAnalytics="G-N03L7B2R6D"
## SEO descirption 
description='這邊是Victor 的技術天地，在這裡我會分享軟體工程師工作的點滴'
theme = 'anatole'
enableRobotsTXT = true
defaultContentLanguage='zh'
fullPostContent = true
hasCJKLanguage=true
summaryLength=100
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
[params]
  readMore = true
  enableMediumZoom=false
  customCss = ["css/custom.css"]
  favicon = 'favicons/'
  profilePicture='images/gravator.jpg'
  gtagId="G-N03L7B2R6D"
  hotjarId = "3836599"
  relatedPosts=true
  numberOfRelatedPosts=3

[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = true
    type = 'basic'
    weight = 80

  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Accomplishments"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "Awards"
  weight = 510
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "Certifications"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
## 設定語系
[languages]   
  [languages.zh]     
    disabled = false
    languageCode = 'zh-TW'     
    languageDirection = 'ltr'     
    languageName = '繁體中文'     
    weight = 1
    summaryLength=150
    [languages.zh.params]
      Title='蔡仔為 Victor Tsai'
      description='這邊是Victor 的技術天地，在這裡我會分享軟體工程師工作的點滴'
     [[languages.zh.menu.main]]
      name="首頁"
      url = "/"
      weight=100
    [[languages.zh.menu.main]]
      name = "文章"
      weight = 200
      identifier = "posts"
      url = "/post/"
    [[languages.zh.menu.main]]
      name = "作品集"
      weight = 300
      identifier = "portfolio"
      url = "/portfolio/"

    [[languages.zh.menu.main]]
      name = "關於我"
      weight = 400
      identifier = "about"
      url = "/about/"

  [languages.en]     
    disabled = false     
    languageCode = 'en-US'     
    languageDirection = 'ltr'     
    languageName = 'English' 
    weight = 2   
    summaryLength=70  
    [languages.en.params]       
      Title = 'Victor Tsai'
      description = 'Interest: Java, Backend Engineering'
    [[languages.en.menu.main]]
      name="Home"
      url = "/en/"
      weight=100
    [[languages.en.menu.main]]
      name = "Post"
      weight = 200
      identifier = "posts"
      url = "/en/post/"

    [[languages.en.menu.main]]
      name = "Portfolio"
      weight = 300
      identifier = "portfolio"
      url = "/en/portfolio/"

    [[languages.en.menu.main]]
      name = "About Me"
      weight = 400
      identifier = "about"
      url = "/en/about/"