baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '我的HUGO'
theme = 'anatole'
enableRobotsTXT = true
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  profilePicture='images/profile.jpg'
  Title='Victor Tsai'
  description='一位 Java工程師'