baseURL = 'http://example.org/'
## 網站的 title 
title = 'Victor 的技術天地'
author='Victor'
isMultiLingual=true
isTranslated=true

## SEO descirption 
description='這邊是Victor 的技術天地，在這裡我會分享軟體工程師工作的點滴'
theme = 'anatole'
enableRobotsTXT = true
defaultContentLanguage='zh'
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  profilePicture='images/gravator.jpg'

## 設定語系
[languages]   
  [languages.zh]     
    disabled = false
    languageCode = 'zh-TW'     
    languageDirection = 'ltr'     
    languageName = '繁體中文'     
    weight = 1    
    [languages.zh.params]
      Title='蔡仔為 Victor'
      description='一位 Java工程師'
     [[languages.zh.menu.main]]
      name="首頁"
      url = "/"
      weight=100
    [[languages.zh.menu.main]]
      name = "文章"
      weight = 200
      identifier = "posts"
      url = "/post/"
    [[languages.zh.menu.main]]
      name = "作品集"
      weight = 300
      identifier = "portfolio"
      url = "/portfolio/"

    [[languages.zh.menu.main]]
      name = "關於我"
      weight = 400
      identifier = "about"
      url = "/about/"

  [languages.en]     
    disabled = false     
    languageCode = 'en-US'     
    languageDirection = 'ltr'     
    languageName = 'English'     
    weight = 2     
    [languages.en.params]       
      Title = 'Victor Tsai'
      description = 'testing description'
    [[languages.en.menu.main]]
      name="Home"
      url = "/en/"
      weight=100
    [[languages.en.menu.main]]
      name = "Post"
      weight = 200
      identifier = "posts"
      url = "/en/post/"

    [[languages.en.menu.main]]
      name = "Portfolio"
      weight = 300
      identifier = "portfolio"
      url = "/en/portfolio/"

    [[languages.en.menu.main]]
      name = "About Me"
      weight = 400
      identifier = "about"
      url = "/en/about/"